### ISSUE TITLE
Can not find module "@blahblah/packageName"

### ISSUE THREAD

**Issue by MichaelGatesDev** [stereobooster/typescript-monorepo#1]
I tried following the same steps with a project of mine, but I just can not get my packages to reference each other.  I keep getting the following error:
`Cannot find module '@ccss-support-manual/common'.ts(2307)`

[Here is a link to my branch where I have it set up like this one](https://github.com/MichaelGatesDev/ccss-support-manual/tree/restructure)

Do you have any idea how I can solve this?

**Comment by stereobooster** [comment]
try to copy all from https://github.com/stereobooster/typescript-monorepo/blob/master/tsconfig.base.json, probably one of those configs required as well

**Comment by mbrowne** [comment]
It seems that the code doesn't match the readme...the readme says to put relative references in each of your packages, e.g. in `packages/stories/tsconfig.json` you might have `"references": [{ "path": "../b" }, { "path": "../c" }, { "path": "../d" }]`. I'm not sure if there's a way to get it working just with `references` in the top-level `tsconfig.json`, but I wasn't able to figure it out if there is.

**Comment by stereobooster** [comment]
Readme is outdated compared to the actual code. Yes it works with top-level only `references`. You can clone this repo and check it

**Comment by mbrowne** [comment]
Thanks...yes, it does work (I just tested it). But it doesn't work if any of the packages other than `stories` depend on each other. e.g. adding the following to `packages/d/src/d.ts` breaks it:

```ts
import { b } from "@stereobooster/b";
```

The error I get is:
> error TS6059: File '/Users/mbrowne/_temp/typescript-monorepo/packages/b/src/B.tsx' is not under 'rootDir' '/Users/mbrowne/_temp/typescript-monorepo/packages/d'. 'rootDir' is expected to contain all source files.

That must be why it didn't work in my project, since I have such dependencies. Adding relative references fixes it, but it would be nice if it were possible to get it working just with all the references in the root `tsconfig.json`.

But still, thank you for this repo—it was a helpful reference :)

**Comment by MichaelGatesDev** [comment]
Thanks for updating the repo -- I was able to finally figure out what I was doing wrong and it all works swell now. You can check the above-linked rep if you want to see how I did it. Changes were merged into the master branch.

**Comment by stereobooster** [comment]
@mbrowne yes there was dependency between `b` and `d` projects. I deleted it by accident and haven't noticed. I will create PR to fix it

**Comment by mbrowne** [comment]
Thanks @stereobooster, looks good :)
