### ISSUE TITLE
Not an issue, but a thank you

### ISSUE THREAD

**Issue by RiaanWest** [stereobooster/typescript-monorepo#11]
I just wanted to leave a note with a big THANK YOU. Being able to reference your setup has enabled me to solve lots of config problems in my monorepo. Fantastic work!

**Comment by stereobooster** [comment]
Thanks for kind words. I improved set up a bit but haven't backported from the [another repository](https://github.com/contiamo/operational-visualizations). You can take a look if you are curious.
